### PR TITLE
bot: ytdl: fix Errno 2 while uploading to drive

### PR DESCRIPTION
**Pull request by gudmeong**
Signed-off-by: GudMeong <privatemymail758@gmail.com>

### CODE REVIEW

**Comment by ronin08** [comment]
awesome man ! now that error no 2 gone. thanks a lot 👍

**Comment by gudmeong** [comment]
> awesome man ! now that error no 2 gone. thanks a lot +1


> awesome man ! now that error no 2 gone. thanks a lot +1

enjoy, I just helped a little

**Comment by gudmeong** [comment]
> awesome man ! now that error no 2 gone. thanks a lot +1

yourwelcome 🤗

**Comment by ronin08** [comment]
> > awesome man ! now that error no 2 gone. thanks a lot +1
> 
> yourwelcome 🤗

yeah .. I tried a lot . Even figured it out that the hack thing was causing the error . But couldn't make it to work . Without any coding knowledge 😅

**Comment by gudmeong** [comment]
> > > awesome man ! now that error no 2 gone. thanks a lot +1
> > 
> > 
> > yourwelcome hugs
> 
> yeah .. I tried a lot . Even figured it out that the hack thing was causing the error . But couldn't make it to work . Without any coding knowledge sweat_smile

me too🙈, i am just beginner. Learning by little things

**Pull request merged**
